### ISSUE TITLE
walktocorpse error

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#10]
so its randomly trying to save the corpse path to the c drive and its getting denied access to use that location I understand how to fix it but would be better if it defaulted those files to the wowclassicgrindbot/path folders and clean them up after corpse retrieved?

[18:14:29 ERR] PerformAction on WalkToCorpseGoal
System.UnauthorizedAccessException: Access to the path 'C:\CorpsePath_20200910181429.json' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Libs.Goals.WalkToCorpseGoal.Reset() in C:\WowClassicGrindBot\Libs\Goals\WalkToCorpseGoal.cs:line 221
   at Libs.Goals.WalkToCorpseGoal.PerformAction() in C:\WowClassicGrindBot\Libs\Goals\WalkToCorpseGoal.cs:line 78
   at Libs.Goals.GoalThread.GoapPerformGoal() in C:\WowClassicGrindBot\Libs\Goals\GoalThread.cs:line 57

**Comment by julianperrott** [comment]
Comment out line 221 in
[WalkToCorpseGoal](https://github.com/julianperrott/WowClassicGrindBot/blob/master/Libs/Goals/WalkToCorpseGoal.cs)

`File.WriteAllText($"../../../../CorpsePath_{DateTime.Now.ToString("yyyyMMddHHmmss")}.json", JsonConvert.SerializeObject(cp));`

**Comment by teehehe** [comment]
> Comment out line 221 in
> [WalkToCorpseGoal](https://github.com/julianperrott/WowClassicGrindBot/blob/master/Libs/Goals/WalkToCorpseGoal.cs)
> 
> `File.WriteAllText($"../../../../CorpsePath_{DateTime.Now.ToString("yyyyMMddHHmmss")}.json", JsonConvert.SerializeObject(cp));`

running the bat as admin fixes the issue just kind of strange it was saving them there will this be updated on the github to reflect or should i manually change mine

**Comment by julianperrott** [comment]
Commented out in source.
