### ISSUE TITLE
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'D7' was not present in the dictionary.

### ISSUE THREAD

**Issue by teehehe** [julianperrott/WowClassicGrindBot#13]
Bot has been running around 4 or 5 hours and got this message. D7 is the drink key bag had 11 of the correct spell id water and it is on the bar as 7.

summon food/water at 4 spell id
D6 is food and correct spellid with 7 in bag.
F10 is the stopattack macro

[05:23:23 INF] ---------------------------------
[05:23:23 INF] New Plan= ParallelGoal
[05:23:24 INF] Low Health [D6] pressing for 250ms
[05:23:24 INF] Low Health [D6] pressing for 250ms
[05:23:24 INF] Drink [D7] pressing for 250ms
[05:23:24 INF] Drink [D7] pressing for 250ms
[05:23:24 INF] Stop attack ERR_SPELL_FAILED_S [F10] pressing for 500ms
[05:23:24 INF] Stop attack ERR_SPELL_FAILED_S [F10] pressing for 500ms
[05:23:24 INF] Stop attack ERR_SPELL_FAILED_S [F10] pressing for 500ms
[05:23:25 INF] Stop attack ERR_SPELL_FAILED_S [F10] pressing for 500ms
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'D7' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Libs.KeyAction.GetCooldownRemaining() in C:\WowClassicGrindBot\Libs\ClassConfig\KeyAction.cs:line 108
   at Libs.KeyAction.<CreateCooldownRequirement>b__109_0() in C:\WowClassicGrindBot\Libs\ClassConfig\KeyAction.cs:line 94
   at Libs.KeyAction.<>c.<CanRun>b__116_0(Requirement r) in C:\WowClassicGrindBot\Libs\ClassConfig\KeyAction.cs:line 158
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Libs.KeyAction.CanRun() in C:\WowClassicGrindBot\Libs\ClassConfig\KeyAction.cs:line 158
   at Libs.Goals.CastingHandler.CanRun(KeyAction item) in C:\WowClassicGrindBot\Libs\Goals\CastingHandler.cs:line 41
   at Libs.Goals.CastingHandler.CastIfReady(KeyAction item, GoapGoal source, Int32 sleepBeforeCast) in C:\WowClassicGrindBot\Libs\Goals\CastingHandler.cs:line 65
   at Libs.Goals.ParallelGoal.<PerformAction>b__9_0(KeyAction key) in C:\WowClassicGrindBot\Libs\Goals\ParallelGoal.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[05:23:25 INF] Interact due to: this.playerReader.LastUIErrorMessage: ERR_SPELL_FAILED_S
[05:23:25 INF] Interact due to: this.playerReader.LastUIErrorMessage: ERR_SPELL_FAILED_S
[
C:\WowClassicGrindBot\BlazorServer>pause

**Comment by julianperrott** [comment]
That's a weird one, the code shouldn't get there if the key is not in the Dictionary. Perhaps a threading issue. I have put a try catch around it to catch it if it ever happens.
