### ISSUE TITLE
Bot consistently crashing after 3-4 hours

### ISSUE THREAD

**Issue by LeonardWarrior** [julianperrott/WowClassicGrindBot#34]
For me the bot always crashes consistently after a couple of hours unmonitored activity. Since I'm not there at the moment of failure I can't be 100% sure of the reason. But Ive gathered the following information as potential causes:

- Usually the chrome BlazorServer has frozen some hours before and is no longer updating. (I guess it should not matter since the bot can run with closing chrome anyway?)

- I shut off my monitor to save power, but the programs are still running. (Put power on after 1h, no problems what I can see)

This is the error code I get:

[01:42:51 INF] SetDirection:- Correcting direction Desired: 5.945, Current: 5.947, distance: 625.552
[01:42:51 INF] [UpArrow] pressing for 400ms
[01:42:52 INF] SetDirection:- Move to next point Desired: 0.841, Current: 9.869, distance: 54355.054
[01:42:52 INF] Target is blacklisted
[01:42:52 INF] [F3] pressing for 400ms
[01:42:52 INF] ---------------------------------
[01:42:52 INF] New Plan= ApproachTargetGoal
[01:42:52 INF] [F10] pressing for 300ms
[01:42:53 WRN] Blacklisted: Target is not a normal mob
Unhandled exception. System.ArgumentOutOfRangeException: Value to add was out of range. (Parameter 'value')
   at System.DateTime.Add(Double value, Int32 scale)
   at System.DateTime.AddSeconds(Double value)
   at Libs.LevelTracker.Update() in C:\Users\Leonard\Desktop\downloads\wowo2\WowClassicGrindBot3\Libs\Addon\LevelTracker.cs:line 45
   at Libs.AddonReader.AddonRefresh() in C:\Users\Leonard\Desktop\downloads\wowo2\WowClassicGrindBot3\Libs\Addon\AddonReader.cs:line 114
   at Libs.BotController.AddonRefreshThread() in C:\Users\Leonard\Desktop\downloads\wowo2\WowClassicGrindBot3\Libs\BotController.cs:line 88
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[01:42:53 INF] Approach target (ApproachTargetAction 1)
[01:42:53 INF] [H] pressing for 99ms

C:\Users\Leonard\Desktop\downloads\wowo2\WowClassicGrindBot3\BlazorServer>pause
Press any key to continue . . .

**Comment by julianperrott** [comment]
It looks to me that for some reason it has failed to read the addon data correctly. This is why the exception has occurred, I have put a check around the code which is throwing the exception, but I think it is just the symptom of a bigger problem.  Perhaps the wow client has disconnected ?

**Comment by LeonardWarrior** [comment]
Im now pretty sure the fault stems from the chrome window freezing and giving the error code:

**An unhandled exception has occurred. See browser dev tools for details. Reload**

This seems to give rise to all kinds of faults, mostly the bot being stuck in some kind of loop. One time it started spinning in its place, looking for a mob and eventually got dc'ed. Another time it started building mesh of triangles and vertices, see below:

[11:33:17 INF]  done
  it got 74112 triangles and 37762 vertices
Got triangles grid (1066.667 , -1066.668) - (1607.8721, -529.96875
[11:33:17 INF] Build hash  74112
[11:33:17 INF] done 165 time 00:00:00.0921007
[11:33:19 INF] Could not find a part of the path 'C:\Users\Leonard\Desktop\downloads\wowo2\WowClassicGrindBot3\PathingApi\PPather\PathInfo\Kalimdor\c_196_194.bin'.
[11:33:19 INF] Loaded c_196_194.bin 0 spots 0 steps
[11:33:23 INF] Could not find a part of the path 'C:\Users\Leonard\Desktop\downloads\wowo2\WowClassicGrindBot3\PathingApi\PPather\PathInfo\Kalimdor\c_197_197.bin'.
[11:33:23 INF] Loaded c_197_197.bin 0 spots 0 steps
[11:33:28 INF] Could not find a part of the path 'C:\Users\Leonard\Desktop\downloads\wowo2\WowClassicGrindBot3\PathingApi\PPather\PathInfo\Kalimdor\c_196_197.bin'.
[11:33:28 INF] Loaded c_196_197.bin 0 spots 0 steps
Got asked for triangles at 154.12247, -0.9800675
Need triangles grid (0.0006713867 , -533.3333) - (533.334, 0
[11:33:32 INF] Extract World\Maps\Kalimdor\Kalimdor_32_31.adt from ..\PathingAPI\MPQ\patch.MPQ
[11:33:32 INF] Reading adt: World\Maps\Kalimdor\Kalimdor_32_31.adt
[11:33:32 INF] Extract world\generic\orc\passive doodads\barrelsandcrates\orccrate03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\cargoboxes\deadminecargoboxes.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\azeroth\westfall\passivedoodads\barrel\westfallbarrel01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\passivedoodads\barrel\brokenbarrel02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\passivedoodads\furniture\containers\sack01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\passivedoodads\furniture\containers\sack02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\barrelsandcrates\orccratebroken03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\passivedoodads\barrel\brokenbarrel01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\barrelsandcrates\orcbarrel04.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\barrelsandcrates\orccratebroken02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\azeroth\elwynn\passivedoodads\pick\pick.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\azeroth\burningsteppes\passivedoodads\trees\burningsteppestree01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\burntstonetree07.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\passivedoodads\barrel\barrel01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\azeroth\burningsteppes\passivedoodads\trees\burningsteppestree02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\kalimdor\stonetalon\passivedoodads\treestumps\burntstonetreestump03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\burntstonetree08.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\kalimdor\desolace\passivedoodads\spearwalls\centaurspearscone.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\signposts\orcsignpost03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\dwarf\passive doodads\gunracks\gunrack01b.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\azeroth\burningsteppes\passivedoodads\orcsleepmats\orcsleepmat02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\deadminepowderkeg\deadminepowderkeg.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\meat\bloodymeat02.m2 from ..\PathingAPI\MPQ\patch.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\meatracks\rawmeatrack01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\passivedoodads\particleemitters\blacksmith_smoke.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\totems\grimtotem02.m2 from ..\PathingAPI\MPQ\patch.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\totems\grimtotem04.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\weapons\tauren_weaponrack01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\archerytargets\archerytargetdwarf01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\archerytargets\archerytargethuman01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\weapons\tauren_weaponlog02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\signposts\woodsignpostworn01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\taurenhutd.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorbreastplatetrim.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorhelmtrim.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorleatherhelmblackflat.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorleatherhelmbrownflat.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorshouldertrim.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorstand.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\clothing\bootsleatherbrown01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\clothing\hangingshirtgreen.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\loom\taurenloomwhite.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\taurenrugs\taurenrug04.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\taurenshirts\taurenshirthangingblue.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\taurenwallhangings\taurenwallhanging01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\taurenwallhangings\taurenwallhanging03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\weapons&armor\humanaxe01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\weapons&armor\humanaxe02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\weapons&armor\humanhammer01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\weapons&armor\humanhammer02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\weapons&armor\humanmace01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\weapons&armor\humanmace02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\weapons&armor\humansword01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\weapons&armor\humansword02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\weapons\orcaxe01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\weapons\orcaxe02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\weapons\orcaxe03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\weapons\orcsword02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\orc\passive doodads\weapons\orcsword03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\taurenrugs\taurenrug01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\taurenrugs\taurenrug02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\taurenwallhangings\taurenwallhanging02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\taurenrugs\taurenrug03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\warharnasses\warharnessfloor04.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\bowls\taurenbowl06.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\bowls\taurenbowl07.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\baskets\largebasket02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\baskets\largebasket03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\baskets\smallbasket02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\sacks\taurensack02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\tauren\passive doodads\sacks\taurensack03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\taurenhutd_000.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\taurenhutd_001.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\taurenhutbig.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorbracertrim.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorbreastplategreen.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorhelmgreen.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:32 INF] Extract world\generic\human\passive doodads\armor\armorleatherbracerblack.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\armor\armorleatherbracerbrown.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\armor\armorleatherhelmblack.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\armor\armorleatherhelmbrown.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\armor\armorleathershirtblack.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\armor\armorleathershirtbrown.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\armor\armorleathershirtorange.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\armor\armorleathershoulderblack.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\armor\armorleathershoulderorange.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\clothing\bootsleatherblack.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\clothing\bootsleatherdark.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\cloth\clothboltblue.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\cloth\clothboltgreen.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\cloth\clothboltred.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\cloth\clothboltwhite.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\cloth\clothspoolblue.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\cloth\clothspoolyellow.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\cloth\clothyarnblue.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\cloth\clothyarnyellow.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\clothing\hangingpantsbrown.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\clothing\hangingpantsgrey.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\human\passive doodads\clothing\hangingshirtbrown.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\orc\passive doodads\shields\orcshield01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\orc\passive doodads\shields\orcshield02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\orc\passive doodads\shields\orcshield03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\tauren\passive doodads\loom\taurenloomblue.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\tauren\passive doodads\drums\taurendrumgiant01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\tauren\passive doodads\drums\taurendrummed01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\tauren\passive doodads\sacks\taurensack01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\generic\tauren\passive doodads\warharnasses\warharnessfloor03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\taurenhutbig_000.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\taurenhutbig_001.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\taurenhutc.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\taurenhutc_000.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\ruinedtaurentepee.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] Extract world\wmo\kalimdor\buildings\taurenhuts\ruinedtaurentepee_000.wmo from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:33 INF] modeli: 0 -64.5 -0
[11:33:33 INF] AddTriangles: x(108.33008 - 143.44336) y(108.33984 - 123.2832) z(108.33984 - 123.2832)
[11:33:33 INF] AddTriangles: x(112.06055 - 139.4082) y(114.83008 - 115.1543) z(114.83008 - 115.1543)
[11:33:33 INF] modeli: 0 -399.5 -0
[11:33:33 INF] AddTriangles: x(110.390625 - 154.58789) y(131.2832 - 126.04883) z(131.2832 - 126.04883)
[11:33:33 INF] AddTriangles: x(108.12891 - 156.875) y(125.3418 - 141.5) z(125.3418 - 141.5)
[11:33:33 INF] modeli: 0 -160 -0
[11:33:33 INF] AddTriangles: x(117.41992 - 136.51367) y(132.58398 - 125.88672) z(132.58398 - 125.88672)
[11:33:33 INF] modeli: 0 -88 -0
[11:33:33 INF] AddTriangles: x(-15.5546875 - 1.7929688) y(-10.421875 - -6.923828) z(-10.421875 - -6.923828)
[11:33:33 INF] wee
[11:33:33 INF]  done
  it got 76675 triangles and 39241 vertices
Got triangles grid (-7.2597656 , -541.9824) - (533.334, 2.8476562
[11:33:33 INF] Build hash  76675
[11:33:33 INF] done 175 time 00:00:00.0913720
Got asked for triangles at 1600.2462, 617.12335
Need triangles grid (1599.9998 , 533.3337) - (2133.333, 1066.667
[11:33:34 INF] Extract World\Maps\Kalimdor\Kalimdor_30_28.adt from ..\PathingAPI\MPQ\patch.MPQ
[11:33:34 INF] Reading adt: World\Maps\Kalimdor\Kalimdor_30_28.adt
[11:33:34 INF] Extract world\generic\human\passive doodads\lanterns\generallantern02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\azeroth\elwynn\passivedoodads\shovel\shovel.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\kalidar\passivedoodads\kalidartrees\kalidartree01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\azeroth\duskwood\passivedoodads\tombs\woodcross01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\azeroth\duskwood\passivedoodads\tombs\woodcross02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\burntstonetree07.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\azeroth\redridge\passivedoodads\rocks\redridgerock03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\stonetree01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\generic\orc\passive doodads\wyvernnests\wyvernnest01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\treestumps\stonetreestump01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\stonetree07.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\treestumps\stonetreestump03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\stonetree06.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\stonetree02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\kalidar\passivedoodads\kalidarharpynest\kalidarnest01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\treestumps\stonetreestump02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\stonetree08.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\kalidar\passivedoodads\kalidarharpynest\kalidarnest02.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\felwood\passivedoodads\tree\felwoodtreesub03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\kalimdor\stonetalon\passivedoodads\trees\stonetree03.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] Extract world\lordaeron\plagueland\passivedoodads\treebarrier\treebarrier01.m2 from ..\PathingAPI\MPQ\common-2.MPQ
[11:33:34 INF] wee
[11:33:34 INF]  done
  it got 83267 triangles and 43225 vertices
Got triangles grid (1590.0928 , 529.8242) - (2133.333, 1069.0928
[11:33:34 INF] Build hash  83267
[11:33:34 INF] done 385 time 00:00:00.1095166
[11:33:35 INF] Could not find a part of the path 'C:\Users\Leonard\Desktop\downloads\wowo2\WowClassicGrindBot3\PathingApi\PPather\PathInfo\Kalimdor\c_198_197.bin'.
[11:33:35 INF] Loaded c_198_197.bin 0 spots 0 steps

On and on until it gets disconnected.

**Comment by julianperrott** [comment]
This should be fixed now.
